// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("sel")
	ScopeName = "github.com/groq/opentelemetry-collector-contrib/receiver/selreceiver"
)

const (
	LogsStability = component.StabilityLevelAlpha
)
